[project]
name = "onchain-analyst"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "humanize>=4.16.0",
    "plotext>=5.3.2",
    "pyfiglet>=1.0.4",
    "rich>=15.0.0",
    "textual>=8.2.8",
    "textual-plotext>=1.0.1",
]

[dependency-groups]
dev = [
    "pytest-asyncio>=1.4.0",
    "pytest-textual-snapshot>=1.1.0",
    "ruff>=0.16.4",
    "textual-dev>=1.8.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
